#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    ImgsearchingAPI-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^imgsearchingapi\.ddev\.site$`)
      
      service: "ImgsearchingAPI-xhgui-80"
      tls: false
      # middlewares:
      #   - "ImgsearchingAPI-redirectHttps"
    ImgsearchingAPI-web-80-http:
      entrypoints:
        - http-8080
      rule: HostRegexp(`^imgsearchingapi\.ddev\.site$`)
      
      service: "ImgsearchingAPI-web-80"
      tls: false
      # middlewares:
      #   - "ImgsearchingAPI-redirectHttps"
    ImgsearchingAPI-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^imgsearchingapi\.ddev\.site$`)
      
      service: "ImgsearchingAPI-web-8025"
      tls: false
      # middlewares:
      #   - "ImgsearchingAPI-redirectHttps"
    
    
    ImgsearchingAPI-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^imgsearchingapi\.ddev\.site$`)
      
      service: "ImgsearchingAPI-xhgui-80"
      
      tls: true
      
    
    
    ImgsearchingAPI-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^imgsearchingapi\.ddev\.site$`)
      
      service: "ImgsearchingAPI-web-80"
      
      tls: true
      
    ImgsearchingAPI-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^imgsearchingapi\.ddev\.site$`)
      
      service: "ImgsearchingAPI-web-8025"
      
      tls: true
      
    

  middlewares:
    ImgsearchingAPI-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    ImgsearchingAPI-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-ImgsearchingAPI-xhgui:80
        
    
    ImgsearchingAPI-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-ImgsearchingAPI-web:80
        
    ImgsearchingAPI-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-ImgsearchingAPI-web:8025
        
    
    
    

