#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    mittnyaprojekt-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^mittnyaprojekt\.ddev\.site$`)
      
      service: "mittnyaprojekt-xhgui-80"
      tls: false
      # middlewares:
      #   - "mittnyaprojekt-redirectHttps"
    mittnyaprojekt-web-80-http:
      entrypoints:
        - http-8080
      rule: HostRegexp(`^mittnyaprojekt\.ddev\.site$`)
      
      service: "mittnyaprojekt-web-80"
      tls: false
      # middlewares:
      #   - "mittnyaprojekt-redirectHttps"
    mittnyaprojekt-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^mittnyaprojekt\.ddev\.site$`)
      
      service: "mittnyaprojekt-web-8025"
      tls: false
      # middlewares:
      #   - "mittnyaprojekt-redirectHttps"
    
    
    mittnyaprojekt-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^mittnyaprojekt\.ddev\.site$`)
      
      service: "mittnyaprojekt-xhgui-80"
      
      tls: true
      
    
    
    mittnyaprojekt-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^mittnyaprojekt\.ddev\.site$`)
      
      service: "mittnyaprojekt-web-80"
      
      tls: true
      
    mittnyaprojekt-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^mittnyaprojekt\.ddev\.site$`)
      
      service: "mittnyaprojekt-web-8025"
      
      tls: true
      
    

  middlewares:
    mittnyaprojekt-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    mittnyaprojekt-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-mittnyaprojekt-xhgui:80
        
    
    mittnyaprojekt-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-mittnyaprojekt-web:80
        
    mittnyaprojekt-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-mittnyaprojekt-web:8025
        
    
    
    

